# Generated by Django 5.0.6 on 2024-07-06 00:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="Modified Date"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, unique=True, verbose_name="Name"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="Modified Date"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, unique=True, verbose_name="Name"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MAC Address Group",
                "verbose_name_plural": "MAC Address Groups",
            },
        ),
        migrations.CreateModel(
            name="GroupUserAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="Modified Date"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Created Date",
                    ),
                ),
                ("create", models.BooleanField(default=False)),
                ("read", models.BooleanField(default=False)),
                ("update", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mar.group"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MAC Address Group: User & Permissions Assignment",
                "verbose_name_plural": "MAC Address Groups: User & Permissions Assignment",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="Modified Date"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, unique=True, verbose_name="Name"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Template Notes"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="Modified Date"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "mac",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mac_address",
                                message="Enter a valid Forescout style MAC Address (lowercase, no spaces, no periods, no hyphens)",
                                regex="^([0-9a-f]){12}$",
                            )
                        ],
                        verbose_name="MAC Address",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Entry Comment"
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Effective Date"
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                (
                    "authorization_parameters",
                    models.BooleanField(
                        default=False, verbose_name="Authorization Parameters?"
                    ),
                ),
                (
                    "deny",
                    models.BooleanField(default=False, verbose_name="Deny Access?"),
                ),
                (
                    "vlan_num",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                4095,
                                message="4095 is the largest allowable VLAN number",
                            ),
                            django.core.validators.MinValueValidator(
                                0, message="0 is the smallest allowable VLAN number"
                            ),
                        ],
                        verbose_name="VLAN Number",
                    ),
                ),
                (
                    "vlan_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="VLAN Name"
                    ),
                ),
                (
                    "mar_comment",
                    models.TextField(blank=True, null=True, verbose_name="MAR Comment"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mar.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mar.group"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_user_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mar.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "MAC",
                "verbose_name_plural": "MACs",
            },
        ),
    ]
