# Generated by Django 5.0.6 on 2024-07-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mar", "0005_load_auth_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="max_expire_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Max Expiration Date from Effective Date (in days)",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="require_expiration",
            field=models.BooleanField(default=False, verbose_name="Require Expiration?"),
        ),
    ]
